apiVersion: v1

kind: Service

metadata:
  name: imahan-api

spec:
  ports:
    - port: 3081
      protocol: TCP
      targetPort: imahan-api
  selector:
    app: imahan-api
  sessionAffinity: None
  type: LoadBalancer
